### ISSUE TITLE
Initializing from an image

### ISSUE THREAD

**Issue by itjustis** [SHI-Labs/Versatile-Diffusion#14]
Hi! Thank you so much, I love VD, so powerful !
Is there any way to also initialize from an image?
using autoencoder or something like encode_first_stage from SD?
thanks!

**Comment by xingqian2018** [comment]
Yea, we are currently implementing new features, and this is among the updates. Please stay tuned for this.

**Comment by xingqian2018** [comment]
@itjustis We just published a new code base that supports this feature. Execute the demo with python app.py and move to Image-Variation. You can control that with the fidelity slidebar.
