### ISSUE TITLE
About train code

### ISSUE THREAD

**Issue by pokameng** [SHI-Labs/Versatile-Diffusion#15]
When will the training code be released?
@honghuis @xingqian2018 @eltociear @anton-l @praeclarumjj3

**Comment by xingqian2018** [comment]
Hi @pokameng, we are currently updating the code base and still debugging on a lot of features, including training. We will try to release ASAP when a stable version is reached!

**Comment by pokameng** [comment]
ok thanks！！！Looking forward training codes!!!




繁华落尽
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SHI-Labs/Versatile-Diffusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月18日(星期天) 下午2:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SHI-Labs/Versatile-Diffusion] About train code (Issue #15)





 
Hi @pokameng, we are currently updating the code base and still debugging on a lot of features, including training. We will try to release ASAP when a stable version is reached!
