### ISSUE TITLE
About training part

### ISSUE THREAD

**Issue by chenaoxuan** [SHI-Labs/Versatile-Diffusion#18]
Hi, when will the training code be open source?

**Comment by xingqian2018** [comment]
Hi @chenaoxuan, unfortunately, we are still updating the code in order to re-exam / formalize the model / the training / in order to reach improved performance. We will also need to have an internal discussion with our professor for training code release, but we are working toward that direction.

**Comment by xingqian2018** [comment]
Same as https://github.com/SHI-Labs/Versatile-Diffusion/issues/15
