### ISSUE TITLE
生成图片太亮

### ISSUE THREAD

**Issue by yeqingzhao** [SHI-Labs/Versatile-Diffusion#19]
你好，在demo上使用Image-Variation时，发现生成的图片偏亮，跟原图的色彩不太搭，请问有方法可以调吗？

**Comment by xingqian2018** [comment]
The demo provides a very simple color calibration (sometimes works well but not ideal). You may try other clever ways. (for instance histogram equalizer)

**Comment by xingqian2018** [comment]
Meanwhile, another trick is you may try image-variation with semantic focus (to manually reduce the influence of the style, any sometime better calibrates the color)
