### ISSUE TITLE
can this already be ran?

### ISSUE THREAD

**Issue by demirklvc** [SHI-Labs/Versatile-Diffusion#2]
hello! can this already be ran? how would the code line for variation look?

**Comment by demirklvc** [comment]
i have an 24gb ram 3090.

**Comment by alleniver** [comment]
env:3090ti
RuntimeError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 23.99 GiB total capacity; 22.72 GiB already allocated; 0 bytes free; 23.20 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.
