### ISSUE TITLE
Zero-Shot Fid

### ISSUE THREAD

**Issue by NieShenRuc** [SHI-Labs/Versatile-Diffusion#20]
Thanks for your excellent work! But I do not find zero-shot fid on MSCOCO of text-to-image, could you please provide more information?

**Comment by xingqian2018** [comment]
Hi, we are still working on that part. On the other hand, we think MSCOCO FID is a temp solution to evaluate text-to-image because diffusion models run low on these scores, which doesn't match the real performance.

**Comment by NieShenRuc** [comment]
Ok， Thaks for your replay！
