### ISSUE TITLE
About watermark detection

### ISSUE THREAD

**Issue by JingyeChen** [SHI-Labs/Versatile-Diffusion#21]
Thanks for your excellent work and your effort on sharing this code!

Here I have one question. In the 4.1 section you mentioned that "the probability containing watermark below 0.3" is reserved. I am wondering how to evaluate the probability that an image contains watermark. Is there an open-source tool?

Again, thanks for reading this issue and I am looking forward to your reply!

**Comment by xingqian2018** [comment]
@JingyeChen I am just using the watermark score provided by the Laion2B dataset. I think it is generated from some watermark detector.
