### ISSUE TITLE
when will release training code?

### ISSUE THREAD

**Issue by pokameng** [SHI-Labs/Versatile-Diffusion#22]
hello bro
I am looking forward to the training codes, but it seems to not releasing.
When will you release training codes?
@xingqian2018

**Comment by xingqian2018** [comment]
We are still working on the major code update. We will post in News when the training code is released.

**Comment by xingqian2018** [comment]
Same as https://github.com/SHI-Labs/Versatile-Diffusion/issues/15

**Comment by pokameng** [comment]
@xingqian2018 
hello!
Thanks for your great works! By the way, when will you release the training codes?
