### ISSUE TITLE
potential for data augmentation

### ISSUE THREAD

**Issue by pribadihcr** [SHI-Labs/Versatile-Diffusion#29]
Hi,
VD in image-variation is it potential for data augmentation? Thanks

**Comment by xingqian2018** [comment]
Maybe I've got this question wrong, but feel free to use VD as a way of data augmentation.

**Comment by khawar-islam** [comment]
Hello @xingqian2018 Thank you for your work. When did you release the image-to-image translation code? I mean by using your pre-trained we will pass the input image VD will generate 4 output images with a different variations.
